quarkus.rest-client.dados-abertos-api.url=https://apidadosabertos.saude.gov.br
quarkus.rest-client.dados-ibge-api.url=https://servicodados.ibge.gov.br/api
quarkus.jackson.property-naming-strategy=SNAKE_CASE

# Ativa o nível de log de rastreamento para o cliente REST do Quarkus
quarkus.log.category."io.quarkus.rest.client.reactive.runtime.ClientResponseFilterLoggingContainer".level=TRACE
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=TRACE

# Opcional: Define o corpo e os headers no log (ajuda a ver o accept: application/json)
quarkus.rest-client.logging.scope=request-response

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.access-control-allow-credentials=true

